permalink: /:year:month:day/:title
url: https://vinizorza.github.io
baseurl: /project

# variables
name: Vinicius Zorzanelli
description: Estudante de Sistemas de Informação, 22 anos. Programo quando não estou vendo série ou jogando. Na área de tecnologia, qualquer coisa de desenvolvimento eu to dentro.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true